# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Question.delete_all
Answer.delete_all
Question.create(title: "A small river named Duden flows by their place and supplies it with the necessary regelialia?", description: "Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.")
Question.create(title: "She packed her seven versalia, put her initial into the belt and made herself on the way?", description: "When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove, the headline of Alphabet Village and the subline of her own road, the Line Lane.")
Question.create(title: "I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine?", description: "I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now.")
Question.create(title: "How is education supposed to make me feel smarter?", description: "Besides, every time I learn something new, it pushes some old stuff out of my brain. Remember when I took that home winemaking course, and I forgot how to drive? I prefer a vehicle that doesn't hurt Mother Earth. It's a go-cart, powered by my own sense of self-satisfaction.")
Question.create(title: "We started out like Romeo and Juliet, but it ended up in tragedy?", description: "You know, the one with all the well meaning rules that don't work out in real life, uh, Christianity. I'm normally not a praying man, but if you're up there, please save me, Superman. Human contact: the final frontier.")
Question.create(title: "Fame was like a drug. But what was even more like a drug were the drugs?", description: "Oh, everything looks bad if you remember it. This is the greatest case of false advertising I've seen since I sued the movie The Never Ending Story. Oh, I'm in no condition to drive. Wait a minute. I don't have to listen to myself. I'm drunk.")

Answer.create(question_id: 1, description: "Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.")
Answer.create(question_id: 1, description: "But nothing the copy said could convince her and so it didn’t take long until a few insidious Copy Writers ambushed her, made her drunk with Longe and Parole and dragged her into their agency, where they abused her for their projects again and again.")
Answer.create(question_id: 1, description: "But nothing the copy said could convince her and so it didn’t take long until a few insidious Copy Writers ambushed her, made her drunk with Longe and Parole and dragged her into their agency, where they abused her for their projects again and again. And if she hasn’t been rewritten, then they are still using her.")
Answer.create(question_id: 2, description: "I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents.")
Answer.create(question_id: 2, description: "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.")
Answer.create(question_id: 2, description: "Your questions have become more redundant and annoying than the last three Highlander movies.")
Answer.create(question_id: 2, description: "You know, the one with all the well meaning rules that don't work out in real life, uh, Christianity. You don't like your job, you don't strike. You go in every day and do it really half-assed. That's the American way.")
Answer.create(question_id: 3, description: "I didn't get rich by signing checks. Ahoy hoy? I've had it with this school, Skinner. Low test scores, class after class of ugly, ugly children… Don't kid yourself, Jimmy. If a cow ever got the chance, he'd eat you and everyone you care about!")
Answer.create(question_id: 3, description: "Marge, it takes two to lie. One to lie and one to listen. A woman is a lot like a refrigerator. Six feet tall, 300 pounds…it makes ice. Kids, we need to talk for a moment about Krusty Brand Chew Goo Gum Like Substance. We all knew it contained spider eggs, but the hantavirus? That came out of left field. So if you're experiencing numbness and/or comas, send five dollars to antidote, PO box…")
Answer.create(question_id: 3, description: "Marge, just about everything's a sin. Y'ever sat down and read this thing? Technically we're not supposed to go to the bathroom. No children have ever meddled with the Republican Party and lived to tell about it.")
Answer.create(question_id: 4, description: "Oh, so they have Internet on computers now! Son, when you participate in sporting events, it's not whether you win or lose: it's how drunk you get. Remember the time he ate my goldfish? And you lied and said I never had goldfish. Then why did I have the bowl, Bart? *Why did I have the bowl?*")
Answer.create(question_id: 4, description: "Your guilty consciences may make you vote Democratic, but secretly you all yearn for a Republican president to lower taxes, brutalize criminals, and rule you like a king! Donuts. Is there anything they can't do?")
Answer.create(question_id: 5, description: "Kids, kids. I'm not going to die. That only happens to bad people. Your guilty consciences may make you vote Democratic, but secretly you all yearn for a Republican president to lower taxes, brutalize criminals, and rule you like a king!")
Answer.create(question_id: 5, description: "I hope I didn't brain my damage. We started out like Romeo and Juliet, but it ended up in tragedy. Brace yourselves gentlemen. According to the gas chromatograph, the secret ingredient is… Love!? Who's been screwing with this thing?")
Answer.create(question_id: 6, description: "Your guilty consciences may make you vote Democratic, but secretly you all yearn for a Republican president to lower taxes, brutalize criminals, and rule you like a king! Oh, so they have Internet on computers now!")
Answer.create(question_id: 6, description: "Donuts. Is there anything they can't do? What's the point of going out? We're just going to wind up back here anyway. Lisa, vampires are make-believe, like elves, gremlins, and Eskimos. We started out like Romeo and Juliet, but it ended up in tragedy.")
